---
title: "Datos de distritos de Costa Rica - flexdashboard y Shiny"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme:
      version: 3
      bootswatch: cosmo
runtime: shiny 
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r paquetes}

library(dplyr)
library(sf)
library(leaflet)
library(DT)
library(readr)
library(ggplot2)
library(plotly)
library(shiny)

```

```{r lectura-datos}
distritos <- 
  st_read(dsn = "C:/Users/Fiorela/Downloads/distritos_simplificados.geojson", quiet = TRUE) %>%
  st_transform(4326)
```

```{r lista-provincias}
# Lista ordenada de provincias + "Todas"
lista_provincias <- unique(distritos$provincia)
lista_provincias <- sort(lista_provincias)
lista_provincias <- c("Todas", lista_provincias)
```

```{r lista-cantones}
# Lista ordenada de provincias + "Todas"
lista_cantones <- unique(distritos$canton)
lista_cantones <- sort(lista_cantones)
lista_cantones <- c("Todas", lista_cantones)
```


Column {.sidebar}
-----------------------------------------------------------------------

```{r filtro}

selectInput(
  inputId = "provincia",
  label = "Provincia",
  choices = lista_provincias,
  selected = "Todos"
)

# Función para filtrar los datos con base en los controles de entrada
filtrarDistritos <- reactive({
  # Valor inicial del objeto que va a retornarse
  distritos_filtrados <- distritos
  
  # Filtrado de distritos por provincia
  if (input$provincia != "Todas") {
    distritos_filtrados <-
      distritos_filtrados %>%
      filter(provincia == input$provincia)
  }
  
  return(distritos_filtrados)
})

```

```{r}
selectInput(
  inputId = "canton",
  label = "Canton",
  choices = lista_cantones,
  selected = "Todos"
) 

# Función para filtrar los datos con base en los controles de entrada
filtrarDistritos <- reactive({
  # Valor inicial del objeto que va a retornarse
  distritos_filtrados <- distritos
  
  # Filtrado de cantones por cantones
  if (input$canton != "Todas") {
    distritos_filtrados <-
      distritos_filtrados %>%
      filter(canton == input$canton)
  }
  
  return(distritos_filtrados)
})
```


Row {data-height=10}
-----------------------------------------------------------------------

### Mapa de distritos

```{r}

renderLeaflet({
  distritos <- filtrarDistritos()

leaflet() %>%
  addTiles(group = "OpenStreetMap") %>%
  addPolygons(data = distritos,
              weight = 1.0,
              group = "Distritos") %>%
  addLayersControl(baseGroups = c("OpenStreetMap"),
                   overlayGroups = c("Distritos"))
})

```

Row {data-height=10}
-----------------------------------------------------------------------

### Tabla de Distritos

```{r}

renderDT({
  distritos <- filtrarDistritos()
  
# Transformación de datos de distritos
distritos <-
  distritos %>%
  select(provincia, canton, distrito, area)

# Visualización de datos de distritos en formato tabular
distritos %>%
  st_drop_geometry() %>%
  datatable(options = list(
    pageLength = 5,
    language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
  ))
})

```

### Gráfico de Distritos

```{r}
renderPlotly({
  distritos <- filtrarDistritos()

# ggplotly - Gráfico de barras simples 
distritos_barras <-
  distritos %>%
  slice_max(area, n = 8) %>% 
  ggplot(aes(x = reorder(distrito, -area), y = area)) +
  geom_bar(stat = "identity") +
  ggtitle("Distritos por área") +
  xlab("Distrito") +
  ylab("Área") 

ggplotly(distritos_barras) %>% config(locale = 'es')
})

```
